project:
  type: book
  output-dir: docs

book:
  title: "IEA Guidance Doc"
  author: "IEA Data WG"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Working Together"
      chapters:
        - How_To_Use_GitHub.qmd
        - Code_of_Conduct.qmd
        - How_to_Contribute.qmd
        - Useful_Resources.qmd
    - part: "ESRs & SoEs"
    - part: "Other Products"
    - part: "Data Management & Best Practices"
    
format:
  html:
    theme: flatly