project:
  type: book
  output-dir: docs

book:
  title: "IEA Guidance Doc"
  author: "IEA Data WG"
  date: last-modified
  cover-image: "images/define system and goals loop.png"
  cover-image-alt: |
    This cover image could be anything
  favicon: "images/favicon.ico"
  repo-url: https://github.com/IEA-Data/IEA_Data_Guidance_Doc
  navbar:
    background: "#276189"
    search: true
    logo: "images/logo-5.png"
    logo-alt: "Integrated Ecosystem Assessment Website"
    logo-href: "https://www.integratedecosystemassessment.noaa.gov"
  chapters:
    - index.qmd
    - part: "Working Together"
      chapters:
        - How_To_Use_GitHub.qmd
        - Code_of_Conduct.qmd
        - How_to_Contribute.qmd
        - Useful_Resources.qmd
    - part: "ESRs & SoEs"
      chapters: 
        - Timelines.qmd
        - Data_Collection.qmd
        - Indicator_Catalogs.qmd
        - Document_Creation.qmd
        - Final_Products_Reports.qmd
    - part: "Other Products"
    - part: "Data Management & Best Practices"
    
format:
  html:
    theme: flatly