---
title: "How to Use GitHub Effectively"
format: html
---

# Features

-   Read Me Files

    -   [READMEs Best Practices](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)

    -   Uses

        -   Organization Wide

        -   Repository Specific

-   Issue Templates

    -   [Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

    -   [Syntax for GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

-   Projects

    -   A project is an adaptable spreadsheet, task-board, and road map that integrates with your issues and pull requests on GitHub to help you plan and track your work effectively. You can create and customize multiple views by filtering, sorting, grouping your issues and pull requests, visualize work with configurable charts, and add custom fields to track metadata specific to your team. Rather than enforcing a specific methodology, a project provides flexible features you can customize to your team\'s needs and processes.

    -   [Projects Quickstart Guide](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects)

-   Discussions

    -   [Discussions Quickstart Guide](https://docs.github.com/en/discussions/quickstart)

# Resources

-   [NMFS OpenSci GitHub and Git](https://nmfs-opensci.github.io/GitHub-Guide/)

-   [Git, GitHub, and R Workshops (Eli Holmes)](https://eeholmes.github.io/teaching/)
