---
title: "Timelines/Calendar"
---

## Alaska

* May  - Preview of Ecosystem and Economic Conditions (PEEC) Workshop
* July - Initial Data Call
* August - First deadline for submissions (usually winter/spring data)
* September - ESR presentation to Crab Plan Team and to Groundfish Plan Team
*           - Second deadline for submissions (usually summer survey data)
* October - ESR presentation to the North Pacific Fishery Management Council, Science and Statistical Committee (crab harvest specifications) 
*         - Risk table development with groundfish stock assessment authors
*         - Submit for Internal review
*         - Submit for Groundifish Plan Team meeting public agenda and review
* November -Present to Groundfish Plan Team
*          - Prepare ESR 'In Briefs'
*          - Submit final Report and 'In Brief' to Council public agenda and review
* December - Present to North Pacific Fishery Management Council (groundfish harvest specifications)
*          - Post ESR and In Brief on NOAA websites

## California Current

* October - Initial Data Call
* November - Data, Figure, and Text Submissions
* December - Complete Data, Figure, and Text Submissions; Develop Primary Themes and Edit Document
* early January - Complete Initial Draft, Coauthor Review and Edits
* late January - Submit for Internal Review
* early February - Submit to Council Briefing Book
* March - Present to Pacific Fishery Management Council

## Gulf/Southeast

## Hawai'i

## Northeast
* August - State of the Ecosystem Kick-off meeting and call for data
* October - Data deadline for new data products and preliminary data
* December - Final data deadline 
           - Preliminary data review
* January - Data synthesis
          - Report writing
* Febuary - Finalize graphics, plots and text
          - Internal review
* March - Presentations to the Mid-Atlantic and New England Fishery Management Council Scientific and Statistical Committees
* April - Presentations to the Mid-Atlantic and New England Fishery Management Councils
* May - Submit final reports to the NOAA Institutional Repository
      - Public presentation
* June - Debrief meeting
* July - Fishery management council indicatory prioritization meetings


